export const INJECTION_TOKENS = {
  USER_REPOSITORY: 'USER_REPOSITORY',
  PASSWORD_HASHER: 'PASSWORD_HASHER',
  ROLE_REPOSITORY: 'ROLE_REPOSITORY',
  PACKAGE_REPOSITORY: 'PACKAGE_REPOSITORY',
  PACKAGE_STATUS_REPOSITORY: 'PACKAGE_STATUS_REPOSITORY',
};
